/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary':    '#070d17',
        'bg-surface':    '#0c182b',
        'bg-overlay':    'rgba(7, 13, 23, 0.85)',
        'brand':         '#1D9E75',
        'border-subtle': 'rgba(29, 158, 117, 0.15)',
        'border-active': '#1D9E75',
        'text-primary':  '#e2e8f0',
        'text-secondary':'rgba(226, 232, 240, 0.55)',
        'emerald-glow':  'rgba(29, 158, 117, 0.12)',
        primary:                    '#68dbae',
        'on-primary':               '#003827',
        'primary-container':        '#26a37a',
        'on-primary-container':     '#003121',
        'inverse-primary':          '#006c4e',
        secondary:                  '#4de082',
        'on-secondary':             '#003919',
        'secondary-container':      '#00b55d',
        'on-secondary-container':   '#003e1c',
        surface:                    '#0f1512',
        'surface-dim':              '#0f1512',
        'surface-bright':           '#343b37',
        'surface-container':        '#1b211e',
        'surface-container-high':   '#252b28',
        'surface-container-highest':'#303633',
        'surface-container-low':    '#171d1a',
        'surface-container-lowest': '#0a0f0d',
        'on-surface':               '#dee4de',
        'on-surface-variant':       '#bccac1',
        'inverse-surface':          '#dee4de',
        'inverse-on-surface':       '#2c322e',
        outline:                    '#87948c',
        'outline-variant':          '#3d4943',
        'surface-tint':             '#68dbae',
        'surface-variant':          '#303633',
        background:                 '#0f1512',
        'on-background':            '#dee4de',
        error:                      '#ffb4ab',
        'on-error':                 '#690005',
        'error-container':          '#93000a',
        'on-error-container':       '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'stack-xs': '4px',
        'stack-sm': '8px',
        section:    '120px',
        inline:     '12px',
        gutter:     '48px',
        component:  '24px',
      },
      fontFamily: {
        'display-xl':      ['Outfit', 'sans-serif'],
        'headline-md':     ['Outfit', 'sans-serif'],
        'body-main':       ['Plus Jakarta Sans', 'sans-serif'],
        'body-strong':     ['Plus Jakarta Sans', 'sans-serif'],
        'nav-link':        ['Plus Jakarta Sans', 'sans-serif'],
        'technical-label': ['Space Grotesk', 'monospace'],
        'code-snippet':    ['"SF Mono"', '"Fira Code"', 'monospace'],
      },
      fontSize: {
        'display-xl':      ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':     ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-main':       ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-strong':     ['14px', { lineHeight: '1.6', fontWeight: '600' }],
        'nav-link':        ['13px', { lineHeight: '1',   fontWeight: '500' }],
        'technical-label': ['11px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '500' }],
        'code-snippet':    ['12px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
