-- Migration 042 (DRAFT) — LLM-distilled multilingual lexicon expansion.
-- Source: docs/research/atlas-paper/phase-1-validation/labels/llm-vocab-mining/
-- Generated by: backend/scripts/propose_migration_042.py
-- Schema version: atlas-migration-042-proposal-v1
-- Minimum vocab confidence: 0.85
--
-- This file is INTENTIONALLY not applied automatically. Pedro reviews
-- each topic block, removes any unsafe term, then applies via Supabase
-- MCP `apply_migration`. After applying, delete v2 assignments for the
-- changed topics and re-run backfill_lexicon_topics.py before
-- re-benchmarking.

BEGIN;

-- agriculture-crop-risk (Agriculture and crop risk)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['crop failure risk', 'harvest threatened by drought', 'pest damage to crops', 'pérdida de cosecha', 'sequía amenaza cultivos', 'plaga agrícola', 'perda de safra', 'seca prejudica lavoura', 'geada danifica plantação', 'raccolto a rischio', 'siccità danneggia colture', 'récolte menacée par la sécheresse', 'risque pour les cultures', 'ernteverlust durch dürre', 'schädlingsbefall landwirtschaft'])
)
WHERE slug = 'agriculture-crop-risk';

-- armed-conflict-escalation (Armed conflict escalation)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['military offensive launched', 'airstrikes intensify', 'ground invasion begins', 'ofensiva militar', 'escalada de violencia', 'bombardeos intensos', 'ofensiva militar intensifica', 'ataques aéreos aumentam', 'escalade militaire', 'offensive terrestre', 'escalation militare', 'bombardamenti intensificati', 'militäroffensive gestartet', 'luftangriffe eskalieren', 'heavy shelling reported'])
)
WHERE slug = 'armed-conflict-escalation';

-- constitutional-institutional-crisis (Constitutional or institutional crisis)
--   existing lexicon size: 0
--   proposed adds: 13
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['constitutional crisis', 'impeachment proceedings', 'crise constitutionnelle', 'dissolution du parlement', 'crisis constitucional', 'golpe institucional', 'crise institucional', 'ruptura constitucional', 'crisi istituzionale', 'crisi costituzionale', 'verfassungskrise', 'staatskrise', 'destitución presidencial'])
)
WHERE slug = 'constitutional-institutional-crisis';

-- corruption-investigation (Corruption investigation)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['corruption probe', 'bribery investigation', 'anticorruption inquiry', 'investigación por corrupción', 'caso de soborno', 'investigado por corrupción', 'investigação por corrupção', 'operação anticorrupção', 'indagato per corruzione', 'inchiesta per corruzione', 'enquête pour corruption', 'mis en examen pour corruption', 'korruptionsermittlung', 'bestechungsvorwürfe', 'ermittlungen wegen korruption'])
)
WHERE slug = 'corruption-investigation';

-- currency-debt-stress (Currency and debt stress)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['currency crisis', 'sovereign debt default', 'debt restructuring talks', 'peso se desploma', 'crisis de deuda soberana', 'reestructuración de deuda', 'crise cambial', 'dívida soberana em risco', 'moratória da dívida', 'crisi del debito sovrano', 'crollo della lira', 'crise de la dette', 'dépréciation monétaire', 'staatsschuldenkrise', 'währungsverfall'])
)
WHERE slug = 'currency-debt-stress';

-- cyberattack-infrastructure (Cyberattack on infrastructure)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['cyberattack on power grid', 'ransomware hits water utility', 'critical infrastructure hacked', 'ataque cibernético infraestructura', 'hackers atacan red eléctrica', 'ciberataque oleoducto', 'ataque hacker infraestrutura', 'ransomware sistema elétrico', 'ciberataque rede de água', 'attacco informatico infrastrutture', 'hacker colpisce rete elettrica', 'cyberattaque réseau électrique', 'attaque informatique infrastructure critique', 'cyberangriff auf stromnetz', 'hackerangriff kritische infrastruktur'])
)
WHERE slug = 'cyberattack-infrastructure';

-- disease-outbreak (Disease outbreak)
--   existing lexicon size: 0
--   proposed adds: 14
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['disease outbreak', 'epidemic spreads', 'cases of infection', 'brote de enfermedad', 'epidemia de', 'surto de doença', 'casos confirmados de', 'focolaio di', 'epidemia in corso', 'épidémie de', 'foyer épidémique', 'ausbruch der krankheit', 'infektionswelle', 'seuchenausbruch'])
)
WHERE slug = 'disease-outbreak';

-- disinformation-influence-operation (Disinformation and influence operation)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['influence operation', 'disinformation campaign', 'coordinated inauthentic behavior', 'campaña de desinformación', 'operación de influencia', 'campanha de desinformação', 'operação de influência', 'campagna di disinformazione', 'operazione di influenza', 'campagne de désinformation', 'opération d''influence', 'desinformationskampagne', 'einflussoperation', 'fake news network', 'manipulation de l''information'])
)
WHERE slug = 'disinformation-influence-operation';

-- election-legitimacy-dispute (Election legitimacy dispute)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['election fraud claims', 'stolen election', 'disputed election results', 'fraude electoral', 'resultados impugnados', 'elección ilegítima', 'fraude nas eleições', 'resultado eleitoral contestado', 'brogli elettorali', 'risultati contestati elezioni', 'fraude électorale', 'résultats électoraux contestés', 'wahlfälschung', 'wahlergebnis angefochten', 'wahlbetrug vorwürfe'])
)
WHERE slug = 'election-legitimacy-dispute';

-- energy-grid-instability (Energy grid instability)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['power grid failure', 'blackout risk', 'grid instability', 'apagón eléctrico', 'colapso de la red eléctrica', 'inestabilidad energética', 'falha na rede elétrica', 'apagão elétrico', 'instabilidade da rede', 'blackout elettrico', 'instabilità della rete elettrica', 'panne du réseau électrique', 'instabilité du réseau énergétique', 'stromausfall netzinstabilität', 'stromnetz zusammenbruch'])
)
WHERE slug = 'energy-grid-instability';

-- flood-landslide-disaster (Flood and landslide disaster)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['flash flood kills', 'landslide buries', 'flood evacuations', 'inundaciones dejan muertos', 'deslizamiento de tierra', 'enchentes deixam vítimas', 'deslizamento de terra mata', 'alluvione travolge', 'frana uccide', 'inondations meurtrières', 'glissement de terrain', 'hochwasser reißt häuser', 'erdrutsch begräbt', 'überschwemmungen fordern tote', 'mudslide sweeps away'])
)
WHERE slug = 'flood-landslide-disaster';

-- food-price-stress (Food price stress)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['food prices surge', 'grocery bills rising', 'cost of food soars', 'precios de alimentos', 'cesta de la compra cara', 'inflación alimentaria', 'preços dos alimentos sobem', 'custo da alimentação', 'caro fare la spesa', 'prezzi alimentari aumentano', 'hausse des prix alimentaires', 'inflation alimentaire', 'lebensmittelpreise steigen', 'teurer einkaufen', 'nahrungsmittelpreise erhöhen'])
)
WHERE slug = 'food-price-stress';

-- forced-displacement (Forced displacement)
--   existing lexicon size: 0
--   proposed adds: 14
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['forced displacement', 'internally displaced persons', 'desplazamiento forzado', 'desplazados internos', 'deslocamento forçado', 'deslocados internos', 'sfollati interni', 'sfollamento forzato', 'déplacement forcé', 'déplacés internes', 'zwangsvertreibung', 'binnenvertriebene', 'mass displacement crisis', 'vertreibung von zivilisten'])
)
WHERE slug = 'forced-displacement';

-- fuel-subsidy-unrest (Fuel subsidy unrest)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['fuel subsidy protest', 'fuel price riots', 'petrol subsidy unrest', 'protestas subsidio combustible', 'disturbios precio gasolina', 'protestos subsídio combustível', 'revolta preço combustível', 'proteste sussidio carburante', 'rivolte prezzo benzina', 'manifestations subvention carburant', 'émeutes prix carburant', 'kraftstoffsubvention proteste', 'benzinpreisunruhen', 'subvención gasolina disturbios', 'spritpreisproteste'])
)
WHERE slug = 'fuel-subsidy-unrest';

-- gang-control-urban-security (Gang control and urban security)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['gang control neighborhood', 'urban gang crackdown', 'street gang violence city', 'control territorial pandillas', 'seguridad urbana pandillas', 'maras controlan barrios', 'gangues controlam favela', 'segurança urbana tráfico', 'operação contra gangues', 'bande criminali quartiere', 'sicurezza urbana gang', 'bandes urbaines sécurité', 'quartiers contrôlés par gangs', 'bandenkriminalität stadtgebiet', 'jugendbanden stadtviertel kontrolle'])
)
WHERE slug = 'gang-control-urban-security';

-- gender-violence-rights (Gender violence and rights)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['violencia de género', 'feminicidio', 'violência doméstica', 'violência contra a mulher', 'violenza di genere', 'femminicidio', 'violences conjugales', 'féminicide', 'häusliche gewalt', 'geschlechtsbezogene gewalt', 'domestic abuse conviction', 'gender-based violence', 'femicide rate', 'restraining order domestic', 'violencia machista'])
)
WHERE slug = 'gender-violence-rights';

-- heat-health-risk (Heat and public health risk)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['heat-related illness', 'extreme heat warning', 'heatstroke deaths', 'golpe de calor', 'ola de calor muertes', 'riesgo sanitario calor', 'mortes por calor', 'onda de calor saúde', 'risco de insolação', 'colpo di calore', 'ondata di calore vittime', 'coup de chaleur', 'canicule risque sanitaire', 'hitzebedingte todesfälle', 'hitzewelle gesundheitsrisiko'])
)
WHERE slug = 'heat-health-risk';

-- housing-cost-pressure (Housing cost pressure)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['rent affordability crisis', 'housing costs soar', 'mortgage burden', 'alquiler inasequible', 'precio de la vivienda sube', 'crise do arrendamento', 'custo da habitação', 'affitti insostenibili', 'caro affitti', 'crise du logement', 'loyers en hausse', 'mietpreise steigen', 'wohnkosten explodieren', 'housing affordability', 'wohnungsnot'])
)
WHERE slug = 'housing-cost-pressure';

-- humanitarian-access-conflict (Humanitarian access under conflict)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['humanitarian corridor blocked', 'aid workers denied entry', 'relief convoy attacked', 'corredor humanitario bloqueado', 'acceso humanitario restringido', 'acesso humanitário bloqueado', 'trabalhadores humanitários impedidos', 'corridoio umanitario', 'aiuti umanitari bloccati', 'couloir humanitaire fermé', 'accès humanitaire entravé', 'humanitäre hilfe blockiert', 'humanitärer korridor gesperrt', 'siege blocks aid delivery', 'ong expulsées zone de guerre'])
)
WHERE slug = 'humanitarian-access-conflict';

-- labor-strike-disruption (Labor strike disruption)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['workers go on strike', 'strike disrupts service', 'union walkout', 'huelga general', 'trabajadores en huelga', 'paro laboral', 'greve dos trabalhadores', 'paralisação geral', 'sciopero generale', 'lavoratori in sciopero', 'grève des travailleurs', 'mouvement de grève', 'streik legt betrieb lahm', 'warnstreik', 'gewerkschaft streik'])
)
WHERE slug = 'labor-strike-disruption';

-- migration-border-pressure (Migration and border pressure)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['border crossings surge', 'asylum seekers detained', 'migrantes en la frontera', 'crisis migratoria', 'travessia irregular', 'fluxo migratório', 'sbarchi migranti', 'flussi migratori irregolari', 'afflux de migrants', 'traversée clandestine', 'illegale migration', 'grenzschutz flüchtlinge', 'irregular migration spike', 'presión migratoria frontera', 'migranten an der grenze'])
)
WHERE slug = 'migration-border-pressure';

-- mining-royalty-risk (Mining and resource safety crisis)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['mine collapse deaths', 'mining accident fatalities', 'trapped miners rescue', 'accidente minero muertos', 'derrumbe en mina', 'mineros atrapados rescate', 'acidente em mina', 'mineiros presos soterrados', 'desastre mineração vítimas', 'crollo miniera vittime', 'minatori intrappolati galleria', 'effondrement mine victimes', 'mineurs piégés secours', 'grubenunglück tote', 'bergwerksunfall eingeschlossen'])
)
WHERE slug = 'mining-royalty-risk';

-- oil-gas-supply-risk (Oil and gas supply risk)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['gas supply disruption', 'oil supply shock', 'pipeline outage', 'suministro de gas en riesgo', 'corte de suministro energético', 'interrupção no fornecimento de gás', 'risco de abastecimento de petróleo', 'fornitura di gas a rischio', 'interruzione forniture petrolio', 'risque d''approvisionnement en gaz', 'rupture d''approvisionnement pétrolier', 'gasversorgung gefährdet', 'ölversorgungsrisiko', 'lng supply crunch', 'lieferstopp erdgas'])
)
WHERE slug = 'oil-gas-supply-risk';

-- press-freedom-crackdown (Press freedom crackdown)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['journalist arrested', 'press freedom crackdown', 'reporter jailed', 'periodista detenido', 'libertad de prensa', 'censura a medios', 'jornalista preso', 'liberdade de imprensa ameaçada', 'censura à imprensa', 'giornalista arrestato', 'libertà di stampa', 'liberté de la presse', 'journaliste emprisonné', 'pressefreiheit eingeschränkt', 'journalist verhaftet'])
)
WHERE slug = 'press-freedom-crackdown';

-- sanctions-diplomatic-pressure (Sanctions and diplomatic pressure)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['economic sanctions imposed', 'sanctions package against', 'diplomatic pressure on', 'sanciones económicas', 'presión diplomática sobre', 'sanções econômicas', 'pressão diplomática', 'sanzioni economiche', 'pressione diplomatica', 'sanctions diplomatiques', 'pression diplomatique sur', 'wirtschaftssanktionen gegen', 'diplomatischer druck auf', 'sanctions regime tightened', 'neue sanktionen verhängt'])
)
WHERE slug = 'sanctions-diplomatic-pressure';

-- student-youth-protest (Student and youth protest)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['student protest', 'campus walkout', 'youth demonstration', 'protesta estudiantil', 'marcha universitaria', 'huelga estudiantil', 'protesto estudantil', 'greve dos estudantes', 'manifestação jovens', 'protesta studentesca', 'corteo studentesco', 'manifestation lycéens', 'grève étudiante', 'studentenprotest', 'schülerstreik'])
)
WHERE slug = 'student-youth-protest';

-- telecom-internet-shutdown (Telecom or internet shutdown)
--   existing lexicon size: 0
--   proposed adds: 14
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['internet shutdown', 'internet blackout', 'telecom blackout', 'corte de internet', 'apagón de internet', 'bloqueo de telecomunicaciones', 'bloqueio de internet', 'apagão de telecomunicações', 'interruzione internet', 'blackout delle telecomunicazioni', 'coupure internet', 'coupure des télécommunications', 'internetsperre', 'internet abgeschaltet'])
)
WHERE slug = 'telecom-internet-shutdown';

-- trade-export-restriction (Trade and export restriction)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['export ban', 'trade embargo', 'export controls tightened', 'restricciones a la exportación', 'veda de exportaciones', 'restrições às exportações', 'proibição de exportação', 'restrizioni all''esportazione', 'divieto di esportazione', 'restrictions aux exportations', 'embargo commercial', 'exportbeschränkungen', 'ausfuhrverbot', 'tariff barriers imposed', 'handelsbeschränkungen verhängt'])
)
WHERE slug = 'trade-export-restriction';

-- transport-corridor-disruption (Transport corridor disruption)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['rail corridor blocked', 'shipping lane disrupted', 'highway closure disrupts freight', 'corredor de transporte bloqueado', 'cierre de autopista interrumpe', 'corredor logístico cortado', 'corredor de transporte interrompido', 'bloqueio na rodovia federal', 'interrupção na ferrovia', 'corridoio ferroviario interrotto', 'blocco autostradale', 'corridor de transport perturbé', 'fermeture de l''axe routier', 'verkehrskorridor gesperrt', 'autobahn gesperrt güterverkehr'])
)
WHERE slug = 'transport-corridor-disruption';

-- water-stress-drought (Water stress and drought)
--   existing lexicon size: 0
--   proposed adds: 15
UPDATE atlas_topics
SET lexicon_terms = ARRAY(
    SELECT DISTINCT unnest(lexicon_terms || ARRAY['water stress', 'drought emergency', 'sequía severa', 'escasez de agua', 'seca prolongada', 'crise hídrica', 'siccità grave', 'emergenza idrica', 'sécheresse prolongée', 'stress hydrique', 'dürre bedroht', 'wasserknappheit', 'aquifer depletion', 'restricciones de agua', 'dürreperiode'])
)
WHERE slug = 'water-stress-drought';

COMMIT;
