-- 089_markets_country_universe_all.sql — L4 markets: the ALL-COUNTRIES
-- descriptive instrument universe (design §5). DATA-ONLY: extends the seed in
-- 088 to every country whose instruments VERIFY against Yahoo's public chart
-- API (markets/build_country_universe.py). basis='descriptive' on every row —
-- true by identity (COP *is* Colombia's currency); no discovery, no #226 gate.
--
-- NO FABRICATION: every symbol below returned >=1 real Yahoo close at build
-- time; tickers that did not resolve were dropped (honest coverage gaps are in
-- docs/research/markets-l4/2026-07-21-country-universe-coverage.md).
--
-- RLS / REVOKE were already set in 088; this migration only INSERTs data.
-- role='export-commodity' rows are a customs fact — stored, but the Brief
-- COUNTRY card must NOT render them as a tile (design §5/§7).

-- ── descriptive metadata (instrument identities) ──
INSERT INTO market_series (symbol, label, asset_class) VALUES
    ('2222.SR', 'Saudi Aramco (Tadawul)', 'equity-single'),
    ('AED=X', 'UAE dirham (USD/AED)', 'fx'),
    ('AFN=X', 'Afghan afghani (USD/AFN)', 'fx'),
    ('ALL=X', 'Albanian lek (USD/ALL)', 'fx'),
    ('AMD=X', 'Armenian dram (USD/AMD)', 'fx'),
    ('AMX', 'America Movil (ADR)', 'equity-single'),
    ('AOA=X', 'Angolan kwanza (USD/AOA)', 'fx'),
    ('ARGT', 'Global X MSCI Argentina ETF', 'equity-etf'),
    ('ARS=X', 'Argentine peso (USD/ARS)', 'fx'),
    ('ASML', 'ASML Holding', 'equity-single'),
    ('AUD=X', 'Australian dollar (AUD/USD)', 'fx'),
    ('AZN=X', 'Azerbaijani manat (USD/AZN)', 'fx'),
    ('BABA', 'Alibaba (ADR)', 'equity-single'),
    ('BAM=X', 'Bosnia convertible mark (USD/BAM)', 'fx'),
    ('BBD=X', 'Barbadian dollar (USD/BBD)', 'fx'),
    ('BDT=X', 'Bangladeshi taka (USD/BDT)', 'fx'),
    ('BHD=X', 'Bahraini dinar (USD/BHD)', 'fx'),
    ('BIF=X', 'Burundian franc (USD/BIF)', 'fx'),
    ('BND=X', 'Brunei dollar (USD/BND)', 'fx'),
    ('BOB=X', 'Bolivian boliviano (USD/BOB)', 'fx'),
    ('BRL=X', 'Brazilian real (USD/BRL)', 'fx'),
    ('BSD=X', 'Bahamian dollar (USD/BSD)', 'fx'),
    ('BWP=X', 'Botswana pula (USD/BWP)', 'fx'),
    ('BYN=X', 'Belarusian ruble (USD/BYN)', 'fx'),
    ('BZD=X', 'Belize dollar (USD/BZD)', 'fx'),
    ('CAD=X', 'Canadian dollar (USD/CAD)', 'fx'),
    ('CC=F', 'Cocoa, front-month', 'ag'),
    ('CDF=X', 'Congolese franc (USD/CDF)', 'fx'),
    ('CHF=X', 'Swiss franc (USD/CHF)', 'fx'),
    ('CL=F', 'WTI crude, front-month', 'energy'),
    ('CLP=X', 'Chilean peso (USD/CLP)', 'fx'),
    ('CNY=X', 'Chinese yuan (USD/CNY)', 'fx'),
    ('COP=X', 'Colombian peso (USD/COP)', 'fx'),
    ('CRC=X', 'Costa Rican colon (USD/CRC)', 'fx'),
    ('CUP=X', 'Cuban peso (USD/CUP)', 'fx'),
    ('CVE=X', 'Cape Verdean escudo (USD/CVE)', 'fx'),
    ('CZK=X', 'Czech koruna (USD/CZK)', 'fx'),
    ('DJF=X', 'Djiboutian franc (USD/DJF)', 'fx'),
    ('DKK=X', 'Danish krone (USD/DKK)', 'fx'),
    ('DOP=X', 'Dominican peso (USD/DOP)', 'fx'),
    ('DZD=X', 'Algerian dinar (USD/DZD)', 'fx'),
    ('ECH', 'iShares MSCI Chile ETF', 'equity-etf'),
    ('EDEN', 'iShares MSCI Denmark ETF', 'equity-etf'),
    ('EFNL', 'iShares MSCI Finland ETF', 'equity-etf'),
    ('EGP=X', 'Egyptian pound (USD/EGP)', 'fx'),
    ('EIDO', 'iShares MSCI Indonesia ETF', 'equity-etf'),
    ('EIRL', 'iShares MSCI Ireland ETF', 'equity-etf'),
    ('EIS', 'iShares MSCI Israel ETF', 'equity-etf'),
    ('ENOR', 'iShares MSCI Norway ETF', 'equity-etf'),
    ('ENZL', 'iShares MSCI New Zealand ETF', 'equity-etf'),
    ('EPHE', 'iShares MSCI Philippines ETF', 'equity-etf'),
    ('EPOL', 'iShares MSCI Poland ETF', 'equity-etf'),
    ('EPU', 'iShares MSCI Peru ETF', 'equity-etf'),
    ('ERN=X', 'Eritrean nakfa (USD/ERN)', 'fx'),
    ('ETB=X', 'Ethiopian birr (USD/ETB)', 'fx'),
    ('EUR=X', 'Euro (EUR/USD)', 'fx'),
    ('EWA', 'iShares MSCI Australia ETF', 'equity-etf'),
    ('EWC', 'iShares MSCI Canada ETF', 'equity-etf'),
    ('EWD', 'iShares MSCI Sweden ETF', 'equity-etf'),
    ('EWG', 'iShares MSCI Germany ETF', 'equity-etf'),
    ('EWH', 'iShares MSCI Hong Kong ETF', 'equity-etf'),
    ('EWI', 'iShares MSCI Italy ETF', 'equity-etf'),
    ('EWJ', 'iShares MSCI Japan ETF', 'equity-etf'),
    ('EWK', 'iShares MSCI Belgium ETF', 'equity-etf'),
    ('EWL', 'iShares MSCI Switzerland ETF', 'equity-etf'),
    ('EWM', 'iShares MSCI Malaysia ETF', 'equity-etf'),
    ('EWN', 'iShares MSCI Netherlands ETF', 'equity-etf'),
    ('EWO', 'iShares MSCI Austria ETF', 'equity-etf'),
    ('EWP', 'iShares MSCI Spain ETF', 'equity-etf'),
    ('EWQ', 'iShares MSCI France ETF', 'equity-etf'),
    ('EWS', 'iShares MSCI Singapore ETF', 'equity-etf'),
    ('EWT', 'iShares MSCI Taiwan ETF', 'equity-etf'),
    ('EWU', 'iShares MSCI United Kingdom ETF', 'equity-etf'),
    ('EWW', 'iShares MSCI Mexico ETF', 'equity-etf'),
    ('EWY', 'iShares MSCI South Korea ETF', 'equity-etf'),
    ('EWZ', 'iShares MSCI Brazil ETF', 'equity-etf'),
    ('EZA', 'iShares MSCI South Africa ETF', 'equity-etf'),
    ('FJD=X', 'Fijian dollar (USD/FJD)', 'fx'),
    ('GBP=X', 'Pound sterling (GBP/USD)', 'fx'),
    ('GC=F', 'Gold, front-month', 'metal'),
    ('GEL=X', 'Georgian lari (USD/GEL)', 'fx'),
    ('GHS=X', 'Ghanaian cedi (USD/GHS)', 'fx'),
    ('GMD=X', 'Gambian dalasi (USD/GMD)', 'fx'),
    ('GNF=X', 'Guinean franc (USD/GNF)', 'fx'),
    ('GREK', 'Global X MSCI Greece ETF', 'equity-etf'),
    ('GTQ=X', 'Guatemalan quetzal (USD/GTQ)', 'fx'),
    ('GXG', 'Global X MSCI Colombia ETF', 'equity-etf'),
    ('GYD=X', 'Guyanese dollar (USD/GYD)', 'fx'),
    ('HDB', 'HDFC Bank (ADR)', 'equity-single'),
    ('HG=F', 'Copper, front-month', 'metal'),
    ('HKD=X', 'Hong Kong dollar (USD/HKD)', 'fx'),
    ('HNL=X', 'Honduran lempira (USD/HNL)', 'fx'),
    ('HTG=X', 'Haitian gourde (USD/HTG)', 'fx'),
    ('HUF=X', 'Hungarian forint (USD/HUF)', 'fx'),
    ('IDR=X', 'Indonesian rupiah (USD/IDR)', 'fx'),
    ('ILS=X', 'Israeli shekel (USD/ILS)', 'fx'),
    ('INDA', 'iShares MSCI India ETF', 'equity-etf'),
    ('INFY', 'Infosys (ADR)', 'equity-single'),
    ('INR=X', 'Indian rupee (USD/INR)', 'fx'),
    ('IQD=X', 'Iraqi dinar (USD/IQD)', 'fx'),
    ('IRR=X', 'Iranian rial (USD/IRR)', 'fx'),
    ('ISK=X', 'Icelandic krona (USD/ISK)', 'fx'),
    ('JMD=X', 'Jamaican dollar (USD/JMD)', 'fx'),
    ('JOD=X', 'Jordanian dinar (USD/JOD)', 'fx'),
    ('JPY=X', 'Japanese yen (USD/JPY)', 'fx'),
    ('KC=F', 'Coffee, front-month', 'ag'),
    ('KES=X', 'Kenyan shilling (USD/KES)', 'fx'),
    ('KHR=X', 'Cambodian riel (USD/KHR)', 'fx'),
    ('KMF=X', 'Comorian franc (USD/KMF)', 'fx'),
    ('KRW=X', 'South Korean won (USD/KRW)', 'fx'),
    ('KSA', 'iShares MSCI Saudi Arabia ETF', 'equity-etf'),
    ('KWD=X', 'Kuwaiti dinar (USD/KWD)', 'fx'),
    ('KZT=X', 'Kazakhstani tenge (USD/KZT)', 'fx'),
    ('LAK=X', 'Lao kip (USD/LAK)', 'fx'),
    ('LBP=X', 'Lebanese pound (USD/LBP)', 'fx'),
    ('LKR=X', 'Sri Lankan rupee (USD/LKR)', 'fx'),
    ('LRD=X', 'Liberian dollar (USD/LRD)', 'fx'),
    ('LSL=X', 'Lesotho loti (USD/LSL)', 'fx'),
    ('LYD=X', 'Libyan dinar (USD/LYD)', 'fx'),
    ('MAD=X', 'Moroccan dirham (USD/MAD)', 'fx'),
    ('MCHI', 'iShares MSCI China ETF', 'equity-etf'),
    ('MDL=X', 'Moldovan leu (USD/MDL)', 'fx'),
    ('MELI', 'MercadoLibre', 'equity-single'),
    ('MGA=X', 'Malagasy ariary (USD/MGA)', 'fx'),
    ('MKD=X', 'Macedonian denar (USD/MKD)', 'fx'),
    ('MMK=X', 'Myanmar kyat (USD/MMK)', 'fx'),
    ('MNT=X', 'Mongolian tugrik (USD/MNT)', 'fx'),
    ('MOP=X', 'Macanese pataca (USD/MOP)', 'fx'),
    ('MRU=X', 'Mauritanian ouguiya (USD/MRU)', 'fx'),
    ('MUR=X', 'Mauritian rupee (USD/MUR)', 'fx'),
    ('MVR=X', 'Maldivian rufiyaa (USD/MVR)', 'fx'),
    ('MWK=X', 'Malawian kwacha (USD/MWK)', 'fx'),
    ('MXN=X', 'Mexican peso (USD/MXN)', 'fx'),
    ('MYR=X', 'Malaysian ringgit (USD/MYR)', 'fx'),
    ('MZN=X', 'Mozambican metical (USD/MZN)', 'fx'),
    ('NAD=X', 'Namibian dollar (USD/NAD)', 'fx'),
    ('NG=F', 'Henry Hub natural gas, front-month', 'energy'),
    ('NGN=X', 'Nigerian naira (USD/NGN)', 'fx'),
    ('NIO=X', 'Nicaraguan cordoba (USD/NIO)', 'fx'),
    ('NOK=X', 'Norwegian krone (USD/NOK)', 'fx'),
    ('NPR=X', 'Nepalese rupee (USD/NPR)', 'fx'),
    ('NSRGY', 'Nestle (ADR)', 'equity-single'),
    ('NVS', 'Novartis (ADR)', 'equity-single'),
    ('NZD=X', 'New Zealand dollar (NZD/USD)', 'fx'),
    ('OMR=X', 'Omani rial (USD/OMR)', 'fx'),
    ('PEN=X', 'Peruvian sol (USD/PEN)', 'fx'),
    ('PGK=X', 'Papua New Guinean kina (USD/PGK)', 'fx'),
    ('PHP=X', 'Philippine peso (USD/PHP)', 'fx'),
    ('PKR=X', 'Pakistani rupee (USD/PKR)', 'fx'),
    ('PLN=X', 'Polish zloty (USD/PLN)', 'fx'),
    ('PYG=X', 'Paraguayan guarani (USD/PYG)', 'fx'),
    ('QAR=X', 'Qatari riyal (USD/QAR)', 'fx'),
    ('QAT', 'iShares MSCI Qatar ETF', 'equity-etf'),
    ('RON=X', 'Romanian leu (USD/RON)', 'fx'),
    ('RSD=X', 'Serbian dinar (USD/RSD)', 'fx'),
    ('RUB=X', 'Russian ruble (USD/RUB)', 'fx'),
    ('RWF=X', 'Rwandan franc (USD/RWF)', 'fx'),
    ('SAP', 'SAP SE (ADR)', 'equity-single'),
    ('SAR=X', 'Saudi riyal (USD/SAR)', 'fx'),
    ('SBD=X', 'Solomon Islands dollar (USD/SBD)', 'fx'),
    ('SCR=X', 'Seychellois rupee (USD/SCR)', 'fx'),
    ('SDG=X', 'Sudanese pound (USD/SDG)', 'fx'),
    ('SEK=X', 'Swedish krona (USD/SEK)', 'fx'),
    ('SGD=X', 'Singapore dollar (USD/SGD)', 'fx'),
    ('SLE=X', 'Sierra Leonean leone (USD/SLE)', 'fx'),
    ('SONY', 'Sony Group (ADR)', 'equity-single'),
    ('SOS=X', 'Somali shilling (USD/SOS)', 'fx'),
    ('SQM', 'Sociedad Quimica y Minera (ADR)', 'equity-single'),
    ('SRD=X', 'Surinamese dollar (USD/SRD)', 'fx'),
    ('STN=X', 'Sao Tome dobra (USD/STN)', 'fx'),
    ('SYP=X', 'Syrian pound (USD/SYP)', 'fx'),
    ('SZL=X', 'Swazi lilangeni (USD/SZL)', 'fx'),
    ('THB=X', 'Thai baht (USD/THB)', 'fx'),
    ('THD', 'iShares MSCI Thailand ETF', 'equity-etf'),
    ('TJS=X', 'Tajikistani somoni (USD/TJS)', 'fx'),
    ('TM', 'Toyota Motor (ADR)', 'equity-single'),
    ('TMT=X', 'Turkmenistani manat (USD/TMT)', 'fx'),
    ('TND=X', 'Tunisian dinar (USD/TND)', 'fx'),
    ('TOP=X', 'Tongan pa''anga (USD/TOP)', 'fx'),
    ('TRY=X', 'Turkish lira (USD/TRY)', 'fx'),
    ('TSM', 'Taiwan Semiconductor (ADR)', 'equity-single'),
    ('TTD=X', 'Trinidad and Tobago dollar (USD/TTD)', 'fx'),
    ('TUR', 'iShares MSCI Turkey ETF', 'equity-etf'),
    ('TWD=X', 'New Taiwan dollar (USD/TWD)', 'fx'),
    ('TZS=X', 'Tanzanian shilling (USD/TZS)', 'fx'),
    ('UAE', 'iShares MSCI UAE ETF', 'equity-etf'),
    ('UAH=X', 'Ukrainian hryvnia (USD/UAH)', 'fx'),
    ('UGX=X', 'Ugandan shilling (USD/UGX)', 'fx'),
    ('UYU=X', 'Uruguayan peso (USD/UYU)', 'fx'),
    ('UZS=X', 'Uzbekistani som (USD/UZS)', 'fx'),
    ('VES=X', 'Venezuelan bolivar (USD/VES)', 'fx'),
    ('VND=X', 'Vietnamese dong (USD/VND)', 'fx'),
    ('VNM', 'VanEck Vietnam ETF', 'equity-etf'),
    ('VUV=X', 'Vanuatu vatu (USD/VUV)', 'fx'),
    ('WST=X', 'Samoan tala (USD/WST)', 'fx'),
    ('XAF=X', 'Central African CFA franc (USD/XAF)', 'fx'),
    ('XOF=X', 'West African CFA franc (USD/XOF)', 'fx'),
    ('YER=X', 'Yemeni rial (USD/YER)', 'fx'),
    ('YPF', 'YPF (ADR)', 'equity-single'),
    ('ZAR=X', 'South African rand (USD/ZAR)', 'fx'),
    ('ZC=F', 'Corn, front-month', 'ag'),
    ('ZMW=X', 'Zambian kwacha (USD/ZMW)', 'fx'),
    ('ZS=F', 'Soybeans, front-month', 'ag'),
    ('ZW=F', 'Wheat, front-month', 'ag')
ON CONFLICT (symbol) DO NOTHING;

-- ── per-country descriptive universe (currency / index / champion / export) ──
INSERT INTO country_instrument_universe (country_code, symbol, role, note) VALUES
    ('AE', 'AED=X', 'currency', 'United Arab Emirates''s currency'),
    ('AE', 'UAE', 'index', 'United Arab Emirates country ETF'),
    ('AE', 'CL=F', 'export-commodity', 'United Arab Emirates top export (customs) — NOT a Brief country-card tile'),
    ('AF', 'AFN=X', 'currency', 'Afghanistan''s currency'),
    ('AL', 'ALL=X', 'currency', 'Albania''s currency'),
    ('AM', 'AMD=X', 'currency', 'Armenia''s currency'),
    ('AO', 'AOA=X', 'currency', 'Angola''s currency'),
    ('AO', 'CL=F', 'export-commodity', 'Angola top export (customs) — NOT a Brief country-card tile'),
    ('AR', 'ARS=X', 'currency', 'Argentina''s currency'),
    ('AR', 'ARGT', 'index', 'Argentina country ETF'),
    ('AR', 'MELI', 'champion', 'Argentina champion'),
    ('AR', 'YPF', 'champion', 'Argentina champion'),
    ('AR', 'ZS=F', 'export-commodity', 'Argentina top export (customs) — NOT a Brief country-card tile'),
    ('AT', 'EUR=X', 'currency', 'Austria shares the euro'),
    ('AT', 'EWO', 'index', 'Austria country ETF'),
    ('AU', 'AUD=X', 'currency', 'Australia''s currency'),
    ('AU', 'EWA', 'index', 'Australia country ETF'),
    ('AU', 'GC=F', 'export-commodity', 'Australia top export (customs) — NOT a Brief country-card tile'),
    ('AZ', 'AZN=X', 'currency', 'Azerbaijan''s currency'),
    ('BA', 'BAM=X', 'currency', 'Bosnia and Herzegovina''s currency'),
    ('BB', 'BBD=X', 'currency', 'Barbados''s currency'),
    ('BD', 'BDT=X', 'currency', 'Bangladesh''s currency'),
    ('BE', 'EUR=X', 'currency', 'Belgium shares the euro'),
    ('BE', 'EWK', 'index', 'Belgium country ETF'),
    ('BF', 'XOF=X', 'currency', 'Burkina Faso''s currency'),
    ('BH', 'BHD=X', 'currency', 'Bahrain''s currency'),
    ('BI', 'BIF=X', 'currency', 'Burundi''s currency'),
    ('BJ', 'XOF=X', 'currency', 'Benin''s currency'),
    ('BN', 'BND=X', 'currency', 'Brunei''s currency'),
    ('BO', 'BOB=X', 'currency', 'Bolivia''s currency'),
    ('BR', 'BRL=X', 'currency', 'Brazil''s currency'),
    ('BR', 'EWZ', 'index', 'Brazil country ETF'),
    ('BR', 'ZS=F', 'export-commodity', 'Brazil top export (customs) — NOT a Brief country-card tile'),
    ('BS', 'BSD=X', 'currency', 'Bahamas''s currency'),
    ('BW', 'BWP=X', 'currency', 'Botswana''s currency'),
    ('BY', 'BYN=X', 'currency', 'Belarus''s currency'),
    ('BZ', 'BZD=X', 'currency', 'Belize''s currency'),
    ('CA', 'CAD=X', 'currency', 'Canada''s currency'),
    ('CA', 'EWC', 'index', 'Canada country ETF'),
    ('CD', 'CDF=X', 'currency', 'DR Congo''s currency'),
    ('CD', 'HG=F', 'export-commodity', 'DR Congo top export (customs) — NOT a Brief country-card tile'),
    ('CF', 'XAF=X', 'currency', 'Central African Republic''s currency'),
    ('CG', 'XAF=X', 'currency', 'Republic of the Congo''s currency'),
    ('CH', 'CHF=X', 'currency', 'Switzerland''s currency'),
    ('CH', 'EWL', 'index', 'Switzerland country ETF'),
    ('CH', 'NSRGY', 'champion', 'Switzerland champion'),
    ('CH', 'NVS', 'champion', 'Switzerland champion'),
    ('CI', 'XOF=X', 'currency', 'Ivory Coast''s currency'),
    ('CI', 'CC=F', 'export-commodity', 'Ivory Coast top export (customs) — NOT a Brief country-card tile'),
    ('CL', 'CLP=X', 'currency', 'Chile''s currency'),
    ('CL', 'ECH', 'index', 'Chile country ETF'),
    ('CL', 'SQM', 'champion', 'Chile champion'),
    ('CL', 'HG=F', 'export-commodity', 'Chile top export (customs) — NOT a Brief country-card tile'),
    ('CM', 'XAF=X', 'currency', 'Cameroon''s currency'),
    ('CN', 'CNY=X', 'currency', 'China''s currency'),
    ('CN', 'MCHI', 'index', 'China country ETF'),
    ('CN', 'BABA', 'champion', 'China champion'),
    ('CO', 'COP=X', 'currency', 'Colombia''s currency'),
    ('CO', 'GXG', 'index', 'Colombia country ETF'),
    ('CO', 'CL=F', 'export-commodity', 'Colombia top export (customs) — NOT a Brief country-card tile'),
    ('CO', 'KC=F', 'export-commodity', 'Colombia top export (customs) — NOT a Brief country-card tile'),
    ('CR', 'CRC=X', 'currency', 'Costa Rica''s currency'),
    ('CU', 'CUP=X', 'currency', 'Cuba''s currency'),
    ('CV', 'CVE=X', 'currency', 'Cape Verde''s currency'),
    ('CY', 'EUR=X', 'currency', 'Cyprus shares the euro'),
    ('CZ', 'CZK=X', 'currency', 'Czechia''s currency'),
    ('DE', 'EUR=X', 'currency', 'Germany shares the euro'),
    ('DE', 'EWG', 'index', 'Germany country ETF'),
    ('DE', 'SAP', 'champion', 'Germany champion'),
    ('DJ', 'DJF=X', 'currency', 'Djibouti''s currency'),
    ('DK', 'DKK=X', 'currency', 'Denmark''s currency'),
    ('DK', 'EDEN', 'index', 'Denmark country ETF'),
    ('DO', 'DOP=X', 'currency', 'Dominican Republic''s currency'),
    ('DZ', 'DZD=X', 'currency', 'Algeria''s currency'),
    ('DZ', 'CL=F', 'export-commodity', 'Algeria top export (customs) — NOT a Brief country-card tile'),
    ('DZ', 'NG=F', 'export-commodity', 'Algeria top export (customs) — NOT a Brief country-card tile'),
    ('EC', 'CL=F', 'export-commodity', 'Ecuador top export (customs) — NOT a Brief country-card tile'),
    ('EE', 'EUR=X', 'currency', 'Estonia shares the euro'),
    ('EG', 'EGP=X', 'currency', 'Egypt''s currency'),
    ('ER', 'ERN=X', 'currency', 'Eritrea''s currency'),
    ('ES', 'EUR=X', 'currency', 'Spain shares the euro'),
    ('ES', 'EWP', 'index', 'Spain country ETF'),
    ('ET', 'ETB=X', 'currency', 'Ethiopia''s currency'),
    ('FI', 'EUR=X', 'currency', 'Finland shares the euro'),
    ('FI', 'EFNL', 'index', 'Finland country ETF'),
    ('FJ', 'FJD=X', 'currency', 'Fiji''s currency'),
    ('FR', 'EUR=X', 'currency', 'France shares the euro'),
    ('FR', 'EWQ', 'index', 'France country ETF'),
    ('GA', 'XAF=X', 'currency', 'Gabon''s currency'),
    ('GB', 'GBP=X', 'currency', 'United Kingdom''s currency'),
    ('GB', 'EWU', 'index', 'United Kingdom country ETF'),
    ('GE', 'GEL=X', 'currency', 'Georgia''s currency'),
    ('GH', 'GHS=X', 'currency', 'Ghana''s currency'),
    ('GH', 'CC=F', 'export-commodity', 'Ghana top export (customs) — NOT a Brief country-card tile'),
    ('GH', 'GC=F', 'export-commodity', 'Ghana top export (customs) — NOT a Brief country-card tile'),
    ('GM', 'GMD=X', 'currency', 'Gambia''s currency'),
    ('GN', 'GNF=X', 'currency', 'Guinea''s currency'),
    ('GQ', 'XAF=X', 'currency', 'Equatorial Guinea''s currency'),
    ('GR', 'EUR=X', 'currency', 'Greece shares the euro'),
    ('GR', 'GREK', 'index', 'Greece country ETF'),
    ('GT', 'GTQ=X', 'currency', 'Guatemala''s currency'),
    ('GW', 'XOF=X', 'currency', 'Guinea-Bissau''s currency'),
    ('GY', 'GYD=X', 'currency', 'Guyana''s currency'),
    ('HK', 'HKD=X', 'currency', 'Hong Kong''s currency'),
    ('HK', 'EWH', 'index', 'Hong Kong country ETF'),
    ('HN', 'HNL=X', 'currency', 'Honduras''s currency'),
    ('HR', 'EUR=X', 'currency', 'Croatia shares the euro'),
    ('HT', 'HTG=X', 'currency', 'Haiti''s currency'),
    ('HU', 'HUF=X', 'currency', 'Hungary''s currency'),
    ('ID', 'IDR=X', 'currency', 'Indonesia''s currency'),
    ('ID', 'EIDO', 'index', 'Indonesia country ETF'),
    ('IE', 'EUR=X', 'currency', 'Ireland shares the euro'),
    ('IE', 'EIRL', 'index', 'Ireland country ETF'),
    ('IL', 'ILS=X', 'currency', 'Israel''s currency'),
    ('IL', 'EIS', 'index', 'Israel country ETF'),
    ('IN', 'INR=X', 'currency', 'India''s currency'),
    ('IN', 'INDA', 'index', 'India country ETF'),
    ('IN', 'HDB', 'champion', 'India champion'),
    ('IN', 'INFY', 'champion', 'India champion'),
    ('IQ', 'IQD=X', 'currency', 'Iraq''s currency'),
    ('IQ', 'CL=F', 'export-commodity', 'Iraq top export (customs) — NOT a Brief country-card tile'),
    ('IR', 'IRR=X', 'currency', 'Iran''s currency'),
    ('IS', 'ISK=X', 'currency', 'Iceland''s currency'),
    ('IT', 'EUR=X', 'currency', 'Italy shares the euro'),
    ('IT', 'EWI', 'index', 'Italy country ETF'),
    ('JM', 'JMD=X', 'currency', 'Jamaica''s currency'),
    ('JO', 'JOD=X', 'currency', 'Jordan''s currency'),
    ('JP', 'JPY=X', 'currency', 'Japan''s currency'),
    ('JP', 'EWJ', 'index', 'Japan country ETF'),
    ('JP', 'SONY', 'champion', 'Japan champion'),
    ('JP', 'TM', 'champion', 'Japan champion'),
    ('KE', 'KES=X', 'currency', 'Kenya''s currency'),
    ('KH', 'KHR=X', 'currency', 'Cambodia''s currency'),
    ('KM', 'KMF=X', 'currency', 'Comoros''s currency'),
    ('KR', 'KRW=X', 'currency', 'South Korea''s currency'),
    ('KR', 'EWY', 'index', 'South Korea country ETF'),
    ('KW', 'KWD=X', 'currency', 'Kuwait''s currency'),
    ('KW', 'CL=F', 'export-commodity', 'Kuwait top export (customs) — NOT a Brief country-card tile'),
    ('KZ', 'KZT=X', 'currency', 'Kazakhstan''s currency'),
    ('KZ', 'CL=F', 'export-commodity', 'Kazakhstan top export (customs) — NOT a Brief country-card tile'),
    ('LA', 'LAK=X', 'currency', 'Laos''s currency'),
    ('LB', 'LBP=X', 'currency', 'Lebanon''s currency'),
    ('LK', 'LKR=X', 'currency', 'Sri Lanka''s currency'),
    ('LR', 'LRD=X', 'currency', 'Liberia''s currency'),
    ('LS', 'LSL=X', 'currency', 'Lesotho''s currency'),
    ('LT', 'EUR=X', 'currency', 'Lithuania shares the euro'),
    ('LU', 'EUR=X', 'currency', 'Luxembourg shares the euro'),
    ('LV', 'EUR=X', 'currency', 'Latvia shares the euro'),
    ('LY', 'LYD=X', 'currency', 'Libya''s currency'),
    ('LY', 'CL=F', 'export-commodity', 'Libya top export (customs) — NOT a Brief country-card tile'),
    ('MA', 'MAD=X', 'currency', 'Morocco''s currency'),
    ('MD', 'MDL=X', 'currency', 'Moldova''s currency'),
    ('ME', 'EUR=X', 'currency', 'Montenegro shares the euro'),
    ('MG', 'MGA=X', 'currency', 'Madagascar''s currency'),
    ('MK', 'MKD=X', 'currency', 'North Macedonia''s currency'),
    ('ML', 'XOF=X', 'currency', 'Mali''s currency'),
    ('MM', 'MMK=X', 'currency', 'Myanmar''s currency'),
    ('MN', 'MNT=X', 'currency', 'Mongolia''s currency'),
    ('MO', 'MOP=X', 'currency', 'Macau''s currency'),
    ('MR', 'MRU=X', 'currency', 'Mauritania''s currency'),
    ('MT', 'EUR=X', 'currency', 'Malta shares the euro'),
    ('MU', 'MUR=X', 'currency', 'Mauritius''s currency'),
    ('MV', 'MVR=X', 'currency', 'Maldives''s currency'),
    ('MW', 'MWK=X', 'currency', 'Malawi''s currency'),
    ('MX', 'MXN=X', 'currency', 'Mexico''s currency'),
    ('MX', 'EWW', 'index', 'Mexico country ETF'),
    ('MX', 'AMX', 'champion', 'Mexico champion'),
    ('MY', 'MYR=X', 'currency', 'Malaysia''s currency'),
    ('MY', 'EWM', 'index', 'Malaysia country ETF'),
    ('MZ', 'MZN=X', 'currency', 'Mozambique''s currency'),
    ('NA', 'NAD=X', 'currency', 'Namibia''s currency'),
    ('NE', 'XOF=X', 'currency', 'Niger''s currency'),
    ('NG', 'NGN=X', 'currency', 'Nigeria''s currency'),
    ('NG', 'CL=F', 'export-commodity', 'Nigeria top export (customs) — NOT a Brief country-card tile'),
    ('NI', 'NIO=X', 'currency', 'Nicaragua''s currency'),
    ('NL', 'EUR=X', 'currency', 'Netherlands shares the euro'),
    ('NL', 'EWN', 'index', 'Netherlands country ETF'),
    ('NL', 'ASML', 'champion', 'Netherlands champion'),
    ('NO', 'NOK=X', 'currency', 'Norway''s currency'),
    ('NO', 'ENOR', 'index', 'Norway country ETF'),
    ('NO', 'CL=F', 'export-commodity', 'Norway top export (customs) — NOT a Brief country-card tile'),
    ('NP', 'NPR=X', 'currency', 'Nepal''s currency'),
    ('NZ', 'NZD=X', 'currency', 'New Zealand''s currency'),
    ('NZ', 'ENZL', 'index', 'New Zealand country ETF'),
    ('OM', 'OMR=X', 'currency', 'Oman''s currency'),
    ('PE', 'PEN=X', 'currency', 'Peru''s currency'),
    ('PE', 'EPU', 'index', 'Peru country ETF'),
    ('PE', 'HG=F', 'export-commodity', 'Peru top export (customs) — NOT a Brief country-card tile'),
    ('PG', 'PGK=X', 'currency', 'Papua New Guinea''s currency'),
    ('PH', 'PHP=X', 'currency', 'Philippines''s currency'),
    ('PH', 'EPHE', 'index', 'Philippines country ETF'),
    ('PK', 'PKR=X', 'currency', 'Pakistan''s currency'),
    ('PL', 'PLN=X', 'currency', 'Poland''s currency'),
    ('PL', 'EPOL', 'index', 'Poland country ETF'),
    ('PT', 'EUR=X', 'currency', 'Portugal shares the euro'),
    ('PY', 'PYG=X', 'currency', 'Paraguay''s currency'),
    ('QA', 'QAR=X', 'currency', 'Qatar''s currency'),
    ('QA', 'QAT', 'index', 'Qatar country ETF'),
    ('QA', 'CL=F', 'export-commodity', 'Qatar top export (customs) — NOT a Brief country-card tile'),
    ('QA', 'NG=F', 'export-commodity', 'Qatar top export (customs) — NOT a Brief country-card tile'),
    ('RO', 'RON=X', 'currency', 'Romania''s currency'),
    ('RS', 'RSD=X', 'currency', 'Serbia''s currency'),
    ('RU', 'RUB=X', 'currency', 'Russia''s currency'),
    ('RU', 'CL=F', 'export-commodity', 'Russia top export (customs) — NOT a Brief country-card tile'),
    ('RU', 'ZW=F', 'export-commodity', 'Russia top export (customs) — NOT a Brief country-card tile'),
    ('RW', 'RWF=X', 'currency', 'Rwanda''s currency'),
    ('SA', 'SAR=X', 'currency', 'Saudi Arabia''s currency'),
    ('SA', 'KSA', 'index', 'Saudi Arabia country ETF'),
    ('SA', '2222.SR', 'champion', 'Saudi Arabia champion'),
    ('SA', 'CL=F', 'export-commodity', 'Saudi Arabia top export (customs) — NOT a Brief country-card tile'),
    ('SB', 'SBD=X', 'currency', 'Solomon Islands''s currency'),
    ('SC', 'SCR=X', 'currency', 'Seychelles''s currency'),
    ('SD', 'SDG=X', 'currency', 'Sudan''s currency'),
    ('SE', 'SEK=X', 'currency', 'Sweden''s currency'),
    ('SE', 'EWD', 'index', 'Sweden country ETF'),
    ('SG', 'SGD=X', 'currency', 'Singapore''s currency'),
    ('SG', 'EWS', 'index', 'Singapore country ETF'),
    ('SI', 'EUR=X', 'currency', 'Slovenia shares the euro'),
    ('SK', 'EUR=X', 'currency', 'Slovakia shares the euro'),
    ('SL', 'SLE=X', 'currency', 'Sierra Leone''s currency'),
    ('SN', 'XOF=X', 'currency', 'Senegal''s currency'),
    ('SO', 'SOS=X', 'currency', 'Somalia''s currency'),
    ('SR', 'SRD=X', 'currency', 'Suriname''s currency'),
    ('ST', 'STN=X', 'currency', 'Sao Tome and Principe''s currency'),
    ('SY', 'SYP=X', 'currency', 'Syria''s currency'),
    ('SZ', 'SZL=X', 'currency', 'Eswatini''s currency'),
    ('TD', 'XAF=X', 'currency', 'Chad''s currency'),
    ('TG', 'XOF=X', 'currency', 'Togo''s currency'),
    ('TH', 'THB=X', 'currency', 'Thailand''s currency'),
    ('TH', 'THD', 'index', 'Thailand country ETF'),
    ('TJ', 'TJS=X', 'currency', 'Tajikistan''s currency'),
    ('TM', 'TMT=X', 'currency', 'Turkmenistan''s currency'),
    ('TN', 'TND=X', 'currency', 'Tunisia''s currency'),
    ('TO', 'TOP=X', 'currency', 'Tonga''s currency'),
    ('TR', 'TRY=X', 'currency', 'Turkey''s currency'),
    ('TR', 'TUR', 'index', 'Turkey country ETF'),
    ('TT', 'TTD=X', 'currency', 'Trinidad and Tobago''s currency'),
    ('TW', 'TWD=X', 'currency', 'Taiwan''s currency'),
    ('TW', 'EWT', 'index', 'Taiwan country ETF'),
    ('TW', 'TSM', 'champion', 'Taiwan champion'),
    ('TZ', 'TZS=X', 'currency', 'Tanzania''s currency'),
    ('UA', 'UAH=X', 'currency', 'Ukraine''s currency'),
    ('UA', 'ZC=F', 'export-commodity', 'Ukraine top export (customs) — NOT a Brief country-card tile'),
    ('UA', 'ZW=F', 'export-commodity', 'Ukraine top export (customs) — NOT a Brief country-card tile'),
    ('UG', 'UGX=X', 'currency', 'Uganda''s currency'),
    ('UY', 'UYU=X', 'currency', 'Uruguay''s currency'),
    ('UZ', 'UZS=X', 'currency', 'Uzbekistan''s currency'),
    ('VE', 'VES=X', 'currency', 'Venezuela''s currency'),
    ('VE', 'CL=F', 'export-commodity', 'Venezuela top export (customs) — NOT a Brief country-card tile'),
    ('VN', 'VND=X', 'currency', 'Vietnam''s currency'),
    ('VN', 'VNM', 'index', 'Vietnam country ETF'),
    ('VU', 'VUV=X', 'currency', 'Vanuatu''s currency'),
    ('WS', 'WST=X', 'currency', 'Samoa''s currency'),
    ('XK', 'EUR=X', 'currency', 'Kosovo shares the euro'),
    ('YE', 'YER=X', 'currency', 'Yemen''s currency'),
    ('ZA', 'ZAR=X', 'currency', 'South Africa''s currency'),
    ('ZA', 'EZA', 'index', 'South Africa country ETF'),
    ('ZM', 'ZMW=X', 'currency', 'Zambia''s currency'),
    ('ZM', 'HG=F', 'export-commodity', 'Zambia top export (customs) — NOT a Brief country-card tile')
ON CONFLICT (country_code, symbol, role) DO NOTHING;
