apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: observatory-web
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '5'
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 60
      containers:
        - image: gcr.io/PROJECT_ID/observatory-web:latest
          ports:
            - name: http1
              containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "https://observatory-api-PROJECT_ID.a.run.app"
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
  traffic:
    - percent: 100
      latestRevision: true
