apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: observatory-api
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/observatory-api:latest
          ports:
            - name: http1
              containerPort: 8000
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_PORT
              value: "8000"
            - name: REDIS_HOST
              value: "REDIS_INSTANCE_IP"
            - name: REDIS_PORT
              value: "6379"
            - name: GDELT_BASE
              value: "http://data.gdeltproject.org/gdeltv2"
            - name: API_BASE_URL
              value: "https://observatory-api-PROJECT_ID.a.run.app"
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
  traffic:
    - percent: 100
      latestRevision: true
