export const THEME_LABELS: Record<string, string> = {
    'GENERAL': 'General News',
    'USPEC_POLITICS_GENERAL1': 'US Politics',
    'CRISISLEX_CRISISLEXREC': 'Crisis Response',
    'TAX_FNCACT': 'Financial Activity',
    'ENV_': 'Environment',
    'TERROR': 'Terrorism',
    'PROTEST': 'Protests',
    'ECON_': 'Economy',
    'MILITARY': 'Military',
    'EDUCATION': 'Education',
    'HEALTH': 'Health',
    'EPU_': 'Policy Uncertainty',
    'WB_': 'World Bank Topic',
    'UN_': 'United Nations',
    'GOV_': 'Government',
    'LEADER': 'Leadership',
    'TAX_': 'Taxation',
    'SOC_': 'Social Issues',
    'MED_': 'Medical',
    'CYBER': 'Cybersecurity',
    'NATURAL_DISASTER': 'Natural Disaster',
    'MANMADE_DISASTER': 'Man-made Disaster',
    'POLITICAL_TURMOIL': 'Political Turmoil',
    'ELECTION': 'Elections',
    'DEMOCRACY': 'Democracy',
    'MOVEMENT_': 'Social Movements',
    'SECURITY': 'Security',
    'REFUGEES': 'Refugees',
    'HUMAN_RIGHTS': 'Human Rights',
    'CORRUPTION': 'Corruption',
    'CRIME': 'Crime',
    'JUSTICE': 'Justice',
    'LEGISLATION': 'Legislation',
    'DIPLOMACY': 'Diplomacy',
    'TRADE': 'Trade',
    'INVESTMENT': 'Investment',
    'INDUSTRY': 'Industry',
    'ENERGY': 'Energy',
    'INFRASTRUCTURE': 'Infrastructure',
    'TECHNOLOGY': 'Technology',
    'SCIENCE': 'Science',
    'ARTS': 'Arts',
    'CULTURE': 'Culture',
    'RELIGION': 'Religion',
    'SPORTS': 'Sports',
    'MEDIA': 'Media',
    'LABOR': 'Labor',
    'AGRICULTURE': 'Agriculture',
    'TRANSPORTATION': 'Transportation',
    'ENVIRONMENT': 'Environment',
    'CLIMATE_CHANGE': 'Climate Change',
    'POLLUTION': 'Pollution',
    'WILDLIFE': 'Wildlife',
    'WATER': 'Water',
    'FOOD': 'Food Security',
    'POVERTY': 'Poverty',
    'INEQUALITY': 'Inequality',
    'GENDER': 'Gender Issues',
    'RACE': 'Racial Issues',
    'INDIGENOUS': 'Indigenous Peoples',
    'MIGRATION': 'Migration',
    'WAR': 'War & Conflict',
    'PEACE': 'Peacekeeping',
    'TERRORISM': 'Terrorism',
    'VIOLENCE': 'Violence',
    'CRISIS': 'Crisis',
    'DISASTER': 'Disaster',
    'EMERGENCY': 'Emergency',
    'AID': 'Humanitarian Aid',
    'DEVELOPMENT': 'Development',
    'FINANCE': 'Finance',
    'BUSINESS': 'Business',
    'MARKET': 'Markets',
    'STOCK': 'Stocks',
    'CURRENCY': 'Currency',
    'INFLATION': 'Inflation',
    'DEBT': 'Debt',
    'TAX': 'Tax',
    'BUDGET': 'Budget',
    'LAW': 'Law',
    'COURT': 'Courts',
    'POLICE': 'Police',
    'PRISON': 'Prisons',
    'RIGHTS': 'Rights',
    'FREEDOM': 'Freedom',
    'CENSORSHIP': 'Censorship',
    'PRIVACY': 'Privacy',
    'SURVEILLANCE': 'Surveillance',
    'INTERNET': 'Internet',
    'SOCIAL_MEDIA': 'Social Media',
    'AI': 'Artificial Intelligence',
    'ROBOTICS': 'Robotics',
    'SPACE': 'Space',
    'BIOTECH': 'Biotechnology',
    'NANOTECH': 'Nanotechnology',
    'NUCLEAR': 'Nuclear',
    'WEAPONS': 'Weapons',
    'ARMS': 'Arms Control',
    'INTELLIGENCE': 'Intelligence',
    'ESPIONAGE': 'Espionage',
    'BORDER': 'Borders',
    'IMMIGRATION': 'Immigration',
    'VISA': 'Visas',
    'TRAVEL': 'Travel',
    'TOURISM': 'Tourism',
    'AVIATION': 'Aviation',
    'MARITIME': 'Maritime',
    'SHIPPING': 'Shipping',
    'LOGISTICS': 'Logistics',
    'SUPPLY_CHAIN': 'Supply Chain',
    'MANUFACTURING': 'Manufacturing',
    'CONSTRUCTION': 'Construction',
    'REAL_ESTATE': 'Real Estate',
    'HOUSING': 'Housing',
    'URBAN': 'Urban Issues',
    'RURAL': 'Rural Issues',
    'LAND': 'Land Use',
    'FORESTRY': 'Forestry',
    'MINING': 'Mining',
    'OIL': 'Oil & Gas',
    'RENEWABLE': 'Renewable Energy',
    'SOLAR': 'Solar Power',
    'WIND': 'Wind Power',
    'HYDRO': 'Hydropower',
    'NUCLEAR_POWER': 'Nuclear Power',
    'COAL': 'Coal',
    'GAS': 'Natural Gas',
    'ELECTRICITY': 'Electricity',
    'GRID': 'Power Grid',
    'BATTERY': 'Batteries',
    'EV': 'Electric Vehicles',
    'AUTOMOTIVE': 'Automotive',
    'AEROSPACE': 'Aerospace',
    'DEFENSE': 'Defense',
    'SECURITY_SERVICES': 'Security Services',
    'CONSULTING': 'Consulting',
    'LEGAL': 'Legal Services',
    'ACCOUNTING': 'Accounting',
    'MARKETING': 'Marketing',
    'ADVERTISING': 'Advertising',
    'PR': 'Public Relations',
    'HR': 'Human Resources',
    'RECRUITMENT': 'Recruitment',
    'TRAINING': 'Training',
    'EDUCATION_HIGHER': 'Higher Education',
    'EDUCATION_K12': 'K-12 Education',
    'RESEARCH': 'Research',
    'ACADEMIA': 'Academia',
    'PUBLISHING': 'Publishing',
    'BROADCASTING': 'Broadcasting',
    'JOURNALISM': 'Journalism',
    'ENTERTAINMENT': 'Entertainment',
    'MOVIES': 'Movies',
    'MUSIC': 'Music',
    'GAMING': 'Gaming',
    'FASHION': 'Fashion',
    'DESIGN': 'Design',
    'ARCHITECTURE': 'Architecture',
    'ART': 'Art',
    'MUSEUM': 'Museums',
    'LIBRARY': 'Libraries',
    'HISTORY': 'History',
    'ARCHAEOLOGY': 'Archaeology',
    'ANTHROPOLOGY': 'Anthropology',
    'SOCIOLOGY': 'Sociology',
    'PSYCHOLOGY': 'Psychology',
    'PHILOSOPHY': 'Philosophy',
    'THEOLOGY': 'Theology',
    'RELIGION_CHRISTIANITY': 'Christianity',
    'RELIGION_ISLAM': 'Islam',
    'RELIGION_JUDAISM': 'Judaism',
    'RELIGION_HINDUISM': 'Hinduism',
    'RELIGION_BUDDHISM': 'Buddhism',
    'RELIGION_OTHER': 'Other Religions',
    'SPIRITUALITY': 'Spirituality',
    'ETHICS': 'Ethics',
    'MORALITY': 'Morality',
    'VALUES': 'Values',
    'CULTURE_POP': 'Pop Culture',
    'CULTURE_TRADITIONAL': 'Traditional Culture',
    'LIFESTYLE': 'Lifestyle',
    'FAMILY': 'Family',
    'PARENTING': 'Parenting',
    'RELATIONSHIPS': 'Relationships',
    'DATING': 'Dating',
    'MARRIAGE': 'Marriage',
    'DIVORCE': 'Divorce',
    'CHILDREN': 'Children',
    'YOUTH': 'Youth',
    'SENIORS': 'Seniors',
    'DISABILITY': 'Disability',
    'ACCESSIBILITY': 'Accessibility',
    'INCLUSION': 'Inclusion',
    'DIVERSITY': 'Diversity',
    'EQUITY': 'Equity',
    'COMMUNITY': 'Community',
    'VOLUNTEERING': 'Volunteering',
    'CHARITY': 'Charity',
    'NONPROFIT': 'Nonprofits',
    'NGO': 'NGOs',
    'ACTIVISM': 'Activism',
    'ADVOCACY': 'Advocacy',
    'LOBBYING': 'Lobbying',
    'CAMPAIGN': 'Campaigns',
    'ELECTION_PRESIDENTIAL': 'Presidential Elections',
    'ELECTION_PARLIAMENTARY': 'Parliamentary Elections',
    'ELECTION_LOCAL': 'Local Elections',
    'VOTING': 'Voting',
    'POLLS': 'Polls',
    'PARTIES': 'Political Parties',
    'POLITICIANS': 'Politicians',
    'LEADERS': 'Leaders',
    'OFFICIALS': 'Officials',
    'BUREAUCRACY': 'Bureaucracy',
    'ADMINISTRATION': 'Administration',
    'REGULATION': 'Regulation',
    'POLICY': 'Policy',
    'REFORM': 'Reform',
    'CONSTITUTION': 'Constitution',
    'DEMOCRACY_LIBERAL': 'Liberal Democracy',
    'DEMOCRACY_ILLIBERAL': 'Illiberal Democracy',
    'AUTHORITARIANISM': 'Authoritarianism',
    'DICTATORSHIP': 'Dictatorship',
    'MONARCHY': 'Monarchy',
    'REPUBLIC': 'Republic',
    'FEDERATION': 'Federation',
    'CONFEDERATION': 'Confederation',
    'UNION': 'Union',
    'ALLIANCE': 'Alliance',
    'COALITION': 'Coalition',
    'PARTNERSHIP': 'Partnership',
    'AGREEMENT': 'Agreement',
    'TREATY': 'Treaty',
    'ACCORD': 'Accord',
    'PROTOCOL': 'Protocol',
    'CONVENTION': 'Convention',
    'DECLARATION': 'Declaration',
    'RESOLUTION': 'Resolution',
    'SANCTIONS': 'Sanctions',
    'EMBARGO': 'Embargo',
    'BOYCOTT': 'Boycott',
    'BLOCKADE': 'Blockade',
    'WAR_CIVIL': 'Civil War',
    'WAR_FOREIGN': 'Foreign War',
    'CONFLICT': 'Conflict',
    'DISPUTE': 'Dispute',
    'TENSION': 'Tension',
    'CRISIS_POLITICAL': 'Political Crisis',
    'CRISIS_ECONOMIC': 'Economic Crisis',
    'CRISIS_SOCIAL': 'Social Crisis',
    'CRISIS_HUMANITARIAN': 'Humanitarian Crisis',
    'CRISIS_ENVIRONMENTAL': 'Environmental Crisis',
    'CRISIS_HEALTH': 'Health Crisis',
    'PANDEMIC': 'Pandemic',
    'EPIDEMIC': 'Epidemic',
    'OUTBREAK': 'Outbreak',
    'VIRUS': 'Virus',
    'DISEASE': 'Disease',
    'INFECTION': 'Infection',
    'VACCINE': 'Vaccine',
    'TREATMENT': 'Treatment',
    'CURE': 'Cure',
    'HOSPITAL': 'Hospitals',
    'CLINIC': 'Clinics',
    'DOCTOR': 'Doctors',
    'NURSE': 'Nurses',
    'PATIENT': 'Patients',
    'INSURANCE': 'Insurance',
    'COVERAGE': 'Coverage',
    'BENEFITS': 'Benefits',
    'WELFARE': 'Welfare',
    'SOCIAL_SECURITY': 'Social Security',
    'PENSION': 'Pensions',
    'RETIREMENT': 'Retirement',
    'UNEMPLOYMENT': 'Unemployment',
    'JOBS': 'Jobs',
    'WAGES': 'Wages',
    'SALARY': 'Salary',
    'INCOME': 'Income',
    'WEALTH': 'Wealth',
    'SAVINGS': 'Savings',
    'INVESTING': 'Investing',
    'BANKING': 'Banking',
    'CREDIT': 'Credit',
    'LOANS': 'Loans',
    'MORTGAGE': 'Mortgage',
    'INTEREST': 'Interest Rates',
    'RATES': 'Rates',
    'FOREX': 'Forex',
    'CRYPTO': 'Crypto',
    'BITCOIN': 'Bitcoin',
    'BLOCKCHAIN': 'Blockchain',
    'FINTECH': 'Fintech',
    'STARTUP': 'Startups',
    'VC': 'Venture Capital',
    'PE': 'Private Equity',
    'IPO': 'IPO',
    'MERGER': 'Mergers',
    'ACQUISITION': 'Acquisitions',
    'CORPORATE': 'Corporate',
    'BUSINESS_SMALL': 'Small Business',
    'ENTREPRENEUR': 'Entrepreneurs',
    'INNOVATION': 'Innovation',
    'R_D': 'R&D',
    'PATENT': 'Patents',
    'COPYRIGHT': 'Copyright',
    'TRADEMARK': 'Trademark',
    'IP': 'Intellectual Property',
    'PIRACY': 'Piracy',
    'COUNTERFEIT': 'Counterfeit',
    'FRAUD': 'Fraud',
    'SCAM': 'Scams',
    'HACKING': 'Hacking',
    'BREACH': 'Data Breach',
    'LEAK': 'Leaks',
    'WHISTLEBLOWER': 'Whistleblowers',
    'SECRETS': 'Secrets',
    'CLASSIFIED': 'Classified',
    'SPY': 'Spies',
    'AGENT': 'Agents',
    'ASSET': 'Assets',
    'TARGET': 'Targets',
    'MISSION': 'Mission',
    'OPERATION': 'Operation',
    'CAMPAIGN_MILITARY': 'Military Campaign',
    'BATTLE': 'Battle',
    'SKIRMISH': 'Skirmish',
    'FIGHT': 'Fight',
    'COMBAT': 'Combat',
    'WARFARE': 'Warfare',
    'TACTICS': 'Tactics',
    'STRATEGY': 'Strategy',
    'COMMAND': 'Command',
    'CONTROL': 'Control',
    'COMMUNICATIONS': 'Communications',
    'LOGISTICS_MILITARY': 'Military Logistics',
    'SUPPLY': 'Supply',
    'EQUIPMENT': 'Equipment',
    'GEAR': 'Gear',
    'UNIFORM': 'Uniforms',
    'RANK': 'Rank',
    'OFFICER': 'Officers',
    'SOLDIER': 'Soldiers',
    'TROOPS': 'Troops',
    'FORCES': 'Forces',
    'ARMY': 'Army',
    'NAVY': 'Navy',
    'AIR_FORCE': 'Air Force',
    'MARINES': 'Marines',
    'COAST_GUARD': 'Coast Guard',
    'SPACE_FORCE': 'Space Force',
    'SPECIAL_FORCES': 'Special Forces',
    'MILITIA': 'Militia',
    'REBELS': 'Rebels',
    'INSURGENTS': 'Insurgents',
    'TERRORISTS': 'Terrorists',
    'EXTREMISTS': 'Extremists',
    'RADICALS': 'Radicals',
    'FUNDAMENTALISTS': 'Fundamentalists',
    'SEPARATISTS': 'Separatists',
    'NATIONALISTS': 'Nationalists',
    'PATRIOTS': 'Patriots',
    'TRAITORS': 'Traitors',
    'SPIES': 'Spies',
    'ENEMIES': 'Enemies',
    'ALLIES': 'Allies',
    'FRIENDS': 'Friends',
    'PARTNERS': 'Partners',
    'NEIGHBORS': 'Neighbors',
    'RIVALS': 'Rivals',
    'COMPETITORS': 'Competitors',
    'OPPONENTS': 'Opponents',
    'ADVERSARIES': 'Adversaries',
    'THREATS': 'Threats',
    'RISKS': 'Risks',
    'DANGERS': 'Dangers',
    'HAZARDS': 'Hazards',
    'SAFETY': 'Safety',
    'SECURITY_NATIONAL': 'National Security',
    'SECURITY_HOMELAND': 'Homeland Security',
    'SECURITY_BORDER': 'Border Security',
    'SECURITY_CYBER': 'Cyber Security',
    'SECURITY_FOOD': 'Food Security',
    'SECURITY_ENERGY': 'Energy Security',
    'SECURITY_WATER': 'Water Security',
    'SECURITY_CLIMATE': 'Climate Security',
    'SECURITY_HEALTH': 'Health Security',
    'SECURITY_ECONOMIC': 'Economic Security',
    'SECURITY_SOCIAL': 'Social Security',
    'SECURITY_HUMAN': 'Human Security',
    'SECURITY_GLOBAL': 'Global Security',
    'SECURITY_REGIONAL': 'Regional Security',
    'SECURITY_LOCAL': 'Local Security',
    'SECURITY_PERSONAL': 'Personal Security',
    'SECURITY_PHYSICAL': 'Physical Security',
    'SECURITY_DIGITAL': 'Digital Security',
    'SECURITY_INFORMATION': 'Information Security',
    'SECURITY_NETWORK': 'Network Security',
    'SECURITY_APPLICATION': 'Application Security',
    'SECURITY_CLOUD': 'Cloud Security',
    'SECURITY_ENDPOINT': 'Endpoint Security',
    'SECURITY_MOBILE': 'Mobile Security',
    'SECURITY_IOT': 'IoT Security',
    'SECURITY_OT': 'OT Security',
    'SECURITY_SCADA': 'SCADA Security',
    'SECURITY_ICS': 'ICS Security',
    'SECURITY_CRITICAL': 'Critical Infrastructure Security',
};

export function getThemeLabel(code: string): string {
    // Check exact match first
    if (THEME_LABELS[code]) return THEME_LABELS[code];
    // Check prefix match
    for (const [prefix, label] of Object.entries(THEME_LABELS)) {
        if (code.startsWith(prefix)) return label;
    }
    // Fallback: clean up the code
    return code.replace(/_/g, ' ').replace(/\d+$/, '').toLowerCase().replace(/\b\w/g, l => l.toUpperCase());
}
