import { FlowsResponse } from './mapTypes'

export const mockFlowsData: FlowsResponse = {
  time_window: '24h',
  generated_at: new Date().toISOString(),
  hotspots: [
    {
      country_code: 'US',
      country_name: 'United States',
      latitude: 37.0902,
      longitude: -95.7129,
      topic_count: 245,
      intensity: 0.85,
      confidence: 0.92,
      top_topics: [
        { label: 'Presidential Election', count: 89 },
        { label: 'Tech Industry', count: 67 },
        { label: 'Climate Policy', count: 45 },
        { label: 'Healthcare Reform', count: 44 },
      ],
    },
    {
      country_code: 'GB',
      country_name: 'United Kingdom',
      latitude: 55.3781,
      longitude: -3.436,
      topic_count: 178,
      intensity: 0.72,
      confidence: 0.88,
      top_topics: [
        { label: 'Brexit Impact', count: 56 },
        { label: 'Economic Concerns', count: 48 },
        { label: 'Royal Family', count: 38 },
        { label: 'NHS Crisis', count: 36 },
      ],
    },
    {
      country_code: 'FR',
      country_name: 'France',
      latitude: 46.2276,
      longitude: 2.2137,
      topic_count: 156,
      intensity: 0.68,
      confidence: 0.85,
      top_topics: [
        { label: 'Pension Reform', count: 52 },
        { label: 'Immigration Debate', count: 44 },
        { label: 'EU Relations', count: 34 },
        { label: 'Energy Crisis', count: 26 },
      ],
    },
    {
      country_code: 'DE',
      country_name: 'Germany',
      latitude: 51.1657,
      longitude: 10.4515,
      topic_count: 189,
      intensity: 0.75,
      confidence: 0.9,
      top_topics: [
        { label: 'Energy Transition', count: 64 },
        { label: 'Economic Outlook', count: 52 },
        { label: 'Defense Spending', count: 38 },
        { label: 'Migration Policy', count: 35 },
      ],
    },
    {
      country_code: 'BR',
      country_name: 'Brazil',
      latitude: -14.235,
      longitude: -51.9253,
      topic_count: 134,
      intensity: 0.62,
      confidence: 0.82,
      top_topics: [
        { label: 'Amazon Deforestation', count: 48 },
        { label: 'Political Tensions', count: 38 },
        { label: 'Economic Recovery', count: 28 },
        { label: 'Carnival Season', count: 20 },
      ],
    },
    {
      country_code: 'JP',
      country_name: 'Japan',
      latitude: 36.2048,
      longitude: 138.2529,
      topic_count: 167,
      intensity: 0.7,
      confidence: 0.87,
      top_topics: [
        { label: 'Tech Innovation', count: 58 },
        { label: 'Aging Population', count: 42 },
        { label: 'North Korea Relations', count: 37 },
        { label: 'Olympics Legacy', count: 30 },
      ],
    },
    {
      country_code: 'CN',
      country_name: 'China',
      latitude: 35.8617,
      longitude: 104.1954,
      topic_count: 298,
      intensity: 0.92,
      confidence: 0.78,
      top_topics: [
        { label: 'Economic Slowdown', count: 92 },
        { label: 'Tech Regulation', count: 78 },
        { label: 'Taiwan Relations', count: 64 },
        { label: 'Zero COVID Exit', count: 64 },
      ],
    },
    {
      country_code: 'IN',
      country_name: 'India',
      latitude: 20.5937,
      longitude: 78.9629,
      topic_count: 223,
      intensity: 0.8,
      confidence: 0.84,
      top_topics: [
        { label: 'Economic Growth', count: 72 },
        { label: 'General Elections', count: 68 },
        { label: 'Tech Sector Boom', count: 48 },
        { label: 'Border Security', count: 35 },
      ],
    },
    {
      country_code: 'AU',
      country_name: 'Australia',
      latitude: -25.2744,
      longitude: 133.7751,
      topic_count: 112,
      intensity: 0.55,
      confidence: 0.86,
      top_topics: [
        { label: 'Climate Action', count: 38 },
        { label: 'Housing Crisis', count: 32 },
        { label: 'Indigenous Rights', count: 24 },
        { label: 'China Relations', count: 18 },
      ],
    },
    {
      country_code: 'CO',
      country_name: 'Colombia',
      latitude: 4.5709,
      longitude: -74.2973,
      topic_count: 98,
      intensity: 0.52,
      confidence: 0.8,
      top_topics: [
        { label: 'Peace Process', count: 32 },
        { label: 'Economic Reform', count: 28 },
        { label: 'Drug Trafficking', count: 22 },
        { label: 'Environmental Protection', count: 16 },
      ],
    },
  ],
  flows: [
    {
      from_country: 'US',
      to_country: 'GB',
      heat: 0.78,
      similarity: 0.82,
      time_delta_minutes: 45,
      shared_topics: ['Tech Industry', 'Economic Concerns'],
      from_coords: [-95.7129, 37.0902],
      to_coords: [-3.436, 55.3781],
    },
    {
      from_country: 'US',
      to_country: 'CN',
      heat: 0.85,
      similarity: 0.76,
      time_delta_minutes: 120,
      shared_topics: ['Tech Regulation', 'Economic Outlook'],
      from_coords: [-95.7129, 37.0902],
      to_coords: [104.1954, 35.8617],
    },
    {
      from_country: 'CN',
      to_country: 'IN',
      heat: 0.72,
      similarity: 0.68,
      time_delta_minutes: 90,
      shared_topics: ['Economic Growth', 'Border Security'],
      from_coords: [104.1954, 35.8617],
      to_coords: [78.9629, 20.5937],
    },
    {
      from_country: 'GB',
      to_country: 'FR',
      heat: 0.68,
      similarity: 0.74,
      time_delta_minutes: 30,
      shared_topics: ['EU Relations', 'Energy Crisis'],
      from_coords: [-3.436, 55.3781],
      to_coords: [2.2137, 46.2276],
    },
    {
      from_country: 'FR',
      to_country: 'DE',
      heat: 0.75,
      similarity: 0.8,
      time_delta_minutes: 25,
      shared_topics: ['Energy Transition', 'EU Relations'],
      from_coords: [2.2137, 46.2276],
      to_coords: [10.4515, 51.1657],
    },
    {
      from_country: 'DE',
      to_country: 'GB',
      heat: 0.65,
      similarity: 0.7,
      time_delta_minutes: 60,
      shared_topics: ['Economic Outlook', 'Defense Spending'],
      from_coords: [10.4515, 51.1657],
      to_coords: [-3.436, 55.3781],
    },
    {
      from_country: 'JP',
      to_country: 'US',
      heat: 0.7,
      similarity: 0.72,
      time_delta_minutes: 180,
      shared_topics: ['Tech Innovation', 'North Korea Relations'],
      from_coords: [138.2529, 36.2048],
      to_coords: [-95.7129, 37.0902],
    },
    {
      from_country: 'BR',
      to_country: 'CO',
      heat: 0.58,
      similarity: 0.65,
      time_delta_minutes: 50,
      shared_topics: ['Environmental Protection', 'Economic Reform'],
      from_coords: [-51.9253, -14.235],
      to_coords: [-74.2973, 4.5709],
    },
    {
      from_country: 'IN',
      to_country: 'JP',
      heat: 0.62,
      similarity: 0.68,
      time_delta_minutes: 110,
      shared_topics: ['Tech Sector Boom', 'Economic Growth'],
      from_coords: [78.9629, 20.5937],
      to_coords: [138.2529, 36.2048],
    },
    {
      from_country: 'AU',
      to_country: 'CN',
      heat: 0.55,
      similarity: 0.6,
      time_delta_minutes: 140,
      shared_topics: ['China Relations', 'Climate Action'],
      from_coords: [133.7751, -25.2744],
      to_coords: [104.1954, 35.8617],
    },
  ],
}
